# 实体类包路径
mybatis:
  type-aliases-package: org.lzk.druid.model

spring:
  datasource:
  # 初始化大小、最小、最大连接数
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10

  # 配置获取连接等待超时的时间
      max-wait: 60000

  # 监控后台账号和密码
      stat-view-servlet:
        login-username: admin
        login-password: admin

  # 配置 StatFilter
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  profiles:
    active: mybatisMulit
