datasource:
  anno1:
    jdbc-url: jdbc:mysql://192.168.11.11:3306/test3?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  anno2:
    jdbc-url: jdbc:mysql://192.168.11.11:3306/test4?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver